[book]
authors = ["Jonathan Opperman"]
language = "en"
multilingual = false
src = "."
title = "QitOps Documentation"

[output.html]
git-repository-url = "https://github.com/qitops/qitops-cli-tools"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/qitops/qitops-cli-tools/edit/master/docs/{path}"
additional-css = ["custom.css"]
additional-js = ["custom.js"]
mathjax-support = false
copy-fonts = true
no-section-label = false
preferred-dark-theme = "navy"
curly-quotes = true
search-enabled = true
search-js = true

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
line-numbers = true
runnable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
